version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/nestjs-backend
      - JWT_SECRET=development_jwt_secret_key_123
      - JWT_EXPIRES_IN=15m
      - CORS_ORIGIN=http://localhost:3000
      - CORS_WHITELIST=http://localhost:3000,http://localhost:3001
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=your_aws_access_key
      - AWS_SECRET_ACCESS_KEY=your_aws_secret_key
      - AWS_S3_BUCKET=your_s3_bucket
      - AWS_EC2_IMAGE_ID=ami-12345678
      - AWS_EC2_INSTANCE_TYPE=t2.micro
      - AWS_EC2_MIN_COUNT=1
      - AWS_EC2_MAX_COUNT=1
      - AWS_EC2_KEY_NAME=your_key_pair_name
      - AWS_EC2_SECURITY_GROUP_IDS=sg-12345678
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 