version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Set DATABASE_TYPE to 'mongodb' or 'postgresql' to switch DBs
      - DATABASE_TYPE=mongodb # or postgresql
      # MongoDB envs
      - MONGODB_URI=mongodb://mongodb:27017
      - DB_NAME=backend-template
      # PostgreSQL envs
      - POSTGRESQL_URL=postgresql://postgres:postgres@postgres:5432/backend-template
      - JWT_SECRET=development_jwt_secret_key_123
      - CORS_WHITELIST=http://localhost:3000
      - GITHUB_REPO_URL=https://github.com/your-username/backend-template
      - AWS_ACCESS_KEY_ID=your_aws_access_key
      - AWS_SECRET_ACCESS_KEY=your_aws_secret_key
      - AWS_REGION=your_aws_region
      - AWS_S3_BUCKET=your_s3_bucket
      - AWS_EC2_IMAGE_ID=your_aws_ec2_image_id
      - AWS_EC2_INSTANCE_TYPE=your_aws_ec2_instance_type
      - AWS_EC2_MIN_COUNT=1
      - AWS_EC2_MAX_COUNT=1
      - AWS_EC2_KEY_NAME=your_aws_ec2_key_name
      - AWS_EC2_SECURITY_GROUP_IDS=your_aws_ec2_security_grouo_ids
    depends_on:
      - mongodb
      - postgres
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend-template
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  postgres_data: 